title: Jason Truesdell | Kawasaki, Japan & Seattle, WA
author: JasonTrue
email: jason@yuzuten.com
description: > # this means to ignore newlines until "baseurl:"
  Jason Truesdell is a software developer, experienced in Ruby,
  C#, Java, JavaScript, and Boo. Web applications, backend services,
  domain driven design, and foolish inconsistency. Loves
  digging into solutions for complex business problems.
  Or even simple ones. Available for contract and full-time work
  from Kawasaki, Japan. Travel ok.

# social links
twitter_username: YuzuTenCo
github_username: JasonTrue
instagram_username: JasonTrue
linkedin_username: jasontruesdell

show_excerpts: true

theme: jekyll-theme-midnight

plugins:
  - "jekyll-github-metadata"

