title: Jason Truesdell | Kawasaki, Japan & Seattle, WA
author: Jason
email: jason@yuzuten.com
description: > # this means to ignore newlines until "baseurl:"
  Jason Truesdell is a software developer, experienced in Ruby,
  C#, Java, JavaScript, and Boo. Web applications, backend services,
  domain driven design, and foolish inconsistency. Loves
  digging into solutions for complex business problems.
  Or even simple ones. Available for contract and full-time work
  from Kawasaki, Japan. Travel ok.

exclude:
  /.idea

# For SEO plugin
social:
  name: Jason Truesdell
  links:
    - https://twitter.com/YuzuTenCo
    - https://www.linkedin.com/in/jasontruesdell

#Also for SEO Plugin, but to support Twitter cards
twitter:
  username: YuzuTenCo
  card: summary

# Social links
# These are only used in some themes (like Minima). I'm now using all
# but the stackoverflow link in my custom theme.

twitter_username: YuzuTenCo
github_username: JasonTrue
instagram_username: jasntru
linkedin_username: jasontruesdell
stackoverflow_profile_url: https://stackoverflow.com/users/13433/jasontrue

show_excerpts: true

# When developing locally you will need to use the theme and a bundler
# override, but when deploying to github you'll need to push it with
# remote_theme set.
#theme: jekyll-theme-jagaimo-one
remote_theme: JasonTrue/jekyll-theme-jagaimo-one

plugins:
  - jekyll-github-metadata
  - jekyll-seo-tag
  - jekyll-feed

navigation:
  Home: /
  Resume: /resume.html
  Repositories: /repositories.html

copyright: "&copy; 2019-2020 Jason Truesdell. All rights reserved."

defaults:
  - scope:
      path: ""
    values:
      image:
        path: https://s.jagaimo.com/images/jason-saginuma-modern-coffee.jpg

google_analytics: UA-52437-5
